export const STUDENT_DOCUMENT_CHECKLIST = [
  {
    code: "CERTIFICATE_10TH",
    name: "Certificate of 10th",
    category: "ACADEMIC",
    requiredCount: 1,
    allowMultiple: false,
  },
  {
    code: "CERTIFICATE_12TH",
    name: "Certificate of 12th",
    category: "ACADEMIC",
    requiredCount: 1,
    allowMultiple: false,
  },
  {
    code: "PASSPORT",
    name: "Passport",
    category: "PERSONAL",
    requiredCount: 1,
    allowMultiple: false,
  },
  {
    code: "PROVISIONAL_CERTIFICATE",
    name: "Provisional Certificate",
    category: "ACADEMIC",
    requiredCount: 1,
    allowMultiple: false,
  },
  {
    code: "BACHELORS_TRANSCRIPTS",
    name: "Bachelors Academic Transcripts",
    category: "ACADEMIC",
    requiredCount: 1,
    allowMultiple: true,
  },
  {
    code: "ORIGINAL_DEGREE",
    name: "Original Degree",
    category: "ACADEMIC",
    requiredCount: 1,
    allowMultiple: false,
  },
  {
    code: "CMM",
    name: "Consolidated Marks Memo",
    category: "ACADEMIC",
    requiredCount: 1,
    allowMultiple: false,
  },
  {
    code: "GRE_GMAT",
    name: "GRE / GMAT",
    category: "TEST_SCORE",
    requiredCount: 1,
    allowMultiple: false,
  },
  {
    code: "MOI",
    name: "Medium of Instruction",
    category: "APPLICATION",
    requiredCount: 1,
    allowMultiple: false,
  },
  {
    code: "SOP",
    name: "Statement of Purpose",
    category: "APPLICATION",
    requiredCount: 1,
    allowMultiple: false,
  },
  {
    code: "LOR",
    name: "Letter of Recommendation",
    category: "APPLICATION",
    requiredCount: 3,
    allowMultiple: true,
  },
  {
    code: "WORK_EXPERIENCE",
    name: "Work Experience",
    category: "APPLICATION",
    requiredCount: 1,
    allowMultiple: true,
  },
  {
    code: "RESUME",
    name: "Resume",
    category: "APPLICATION",
    requiredCount: 1,
    allowMultiple: false,
  },
  {
    code: "FINANCIAL_AFFIDAVIT",
    name: "Financial Affidavit",
    category: "LOAN_PARENT",
    requiredCount: 1,
    allowMultiple: false,
  },
  {
    code: "FINANCIAL_STATEMENT",
    name: "Financial Statement",
    category: "LOAN_STUDENT",
    requiredCount: 1,
    allowMultiple: true,
  },
  {
    code: "EDUCATION_LOAN",
    name: "Education Loan",
    category: "LOAN_STUDENT",
    requiredCount: 1,
    allowMultiple: true,
  },
  {
    code: "COURSE_COMPLETION_NOC",
    name: "Course Completion Certificate or NOC",
    category: "ACADEMIC",
    requiredCount: 1,
    allowMultiple: false,
  },
  {
    code: "ENGLISH_PROFICIENCY",
    name: "IELTS / TOEFL / PTE / Duolingo",
    category: "TEST_SCORE",
    requiredCount: 1,
    allowMultiple: true,
  },
] as const;

export type StudentDocumentChecklistItem =
  (typeof STUDENT_DOCUMENT_CHECKLIST)[number];
